FROM markuseggenbauer/cpp-base.alpine:latest

RUN apk add --no-cache \
    git \
    gdb \
    ccache

RUN adduser --disabled-password --gecos "" developer


# install and configure zsh
RUN apk add --no-cache \
    curl \
    zsh
    
USER developer
RUN sh -c "$(curl -L https://github.com/deluan/zsh-in-docker/releases/download/v1.1.2/zsh-in-docker.sh)" -- \
    -t "af-magic" \
    -p "git"

RUN conan config set general.cmake_generator=Ninja
RUN conan profile new default --detect
RUN conan profile update settings.compiler.libcxx=libstdc++11 default

USER root
RUN apk del curl

USER developer
WORKDIR /home/developer

ENTRYPOINT ["/bin/sh", "-c", "while sleep 1000; do :; done"]
