name: Build and Publish Docker image
on:
  push:
    branches:
      - master
    paths:
      - Dockerfile.cpp-base.alpine
      - Dockerfile.cpp-dev.alpine
  workflow_dispatch:
    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push base
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.cpp-base.alpine
          platforms: linux/amd64,linux/arm64
          push: true
          tags: markuseggenbauer/cpp-base.alpine:latest
      -
        name: Build and push dev
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.cpp-dev.alpine
          platforms: linux/amd64,linux/arm64
          push: true
          tags: markuseggenbauer/cpp-dev.alpine:latest
